## Programming Assignment 08

<pre>
1.	Write a Python Program to Add Two Matrices?
2.	Write a Python Program to Multiply Two Matrices?
3.	Write a Python Program to Transpose a Matrix?
4.	Write a Python Program to Sort Words in Alphabetic Order?
5.	Write a Python Program to Remove Punctuation From a String?
<pre>


1.	Write a Python Program to Add Two Matrices?


In [17]:
import numpy as np
def matrix_add(mat1,mat2):
    rows,columns  = mat1.shape 
    #ans = np.zeros_like(mat1)
    if mat1.shape !=mat2.shape:
        return "Error: addition not possible as matrices are having different dimensinos:"
    else:
        for i in range(rows):
            for j in range(columns):
                mat1[i,j] += mat2[i,j]
        return mat1
        

mat1 = np.array([[1,2,4],[3,4,4]])
mat2 = np.array([[1,2,5],[4,5,5]])
ans = matrix_add(mat1,mat2)
print(ans)

[[2 4 9]
 [7 9 9]]


2.	Write a Python Program to Multiply Two Matrices?


In [20]:
def matrix_product(mat1,mat2):
    rows1,columns1 = mat1.shape
    rows2,columns2 = mat2.shape
    if columns1!=rows2:
        print( "Multiplication not possible")
        return False
    else:
        # code here
        return np.dot(mat1,mat2)

mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[1,2],[4,5]])
ans = matrix_product(mat1,mat2)
print(ans)

[[ 9 12]
 [19 26]]


3.	Write a Python Program to Transpose a Matrix?


In [45]:
def Transpose_matrix(mat1):
    rows, columns = mat1.shape
    ans = np.zeros(mat1.size).reshape(columns,rows)
    for i in range(rows):
        for j in range(columns):
            ans[j,i] = mat1[i,j]
    return ans




mat1 = np.array([[1,2,3,3],[4,5,6,5],[2,3,4,5]])
print(f"Original matrix: \n {mat1} \n")

print(f"Transposed matrix: ")
print(Transpose_matrix(mat1))

Original matrix: 
 [[1 2 3 3]
 [4 5 6 5]
 [2 3 4 5]] 

Transposed matrix: 
[[1. 4. 2.]
 [2. 5. 3.]
 [3. 6. 4.]
 [3. 5. 5.]]


4.	Write a Python Program to Sort Words in Alphabetic Order?


In [51]:
word = "write Any word you want here"

word.capitalize()

'Write any word you want here'

5.	Write a Python Program to Remove Punctuation From a String?